config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :feeds, only: %i[index new create] do
    member do
      get :entries
    end
  end

  resources :entries, only: [:index] do
    collection do
      get :search
    end
  end

  root 'static#index'

  namespace :api, defaults: { format: 'json' } do
    resources :search, only: '' do
      collection do
        get :entries
        get :feeds
      end
    end

    resources :webhooks

    resources :tokens, only: [:create] do
      collection do
        get :current
        post :refresh
      end
    end
    resources :feeds, only: %i[index show create] do
      collection do
        get :popular
      end
      resources :entries, only: %i[index show] do
        member do
          get :tags
        end
      end
      resources :logs, only: %i[index show]
      resources :webhooks
    end
  end
end

app/views/shared/_entries.html.erb
<% if entries.present? %>
  <div class="mt-5 mb-5">
    <% if @feed %>
      result <strong><%= @pagy.count %></strong> entries 
      <% if @timing %>
        <span class="text-gray-500">(<%=  @timing.real.round(4) %> sec)</span>
      <% end %>
    <% else %>
      <%= latest ? 'in the last 24 hours' : '' %> result <strong><%= @pagy.count %></strong> entries from <strong><%= entries.pluck(:feed_id).uniq.size %></strong> feeds <span class="text-gray-500">(<%=  @timing.real.round(4) %> sec)</span>
    <% end %>

    <% if params[:q].present? %>
      <div class="float-right rounded  bg-gray-100 border hover:underline border-gray-300 px-2 text-gray-600 md:flex hidden ml-1">
        <%= link_to 'rss', search_entries_path(format: 'rss', q: params[:q]), title: 'RSS feed URL', target: '_blank' %>
      </div>
    <% end %>

    <div class="float-right rounded  bg-gray-100 border hover:underline border-gray-300 px-2 text-gray-600 md:flex hidden">
      <% if @feed %>
          <%= link_to 'csv', entries_feed_path(id: @feed.id, q: params[:q], format: 'csv'), title: 'export feed entries as csv' %>
      <% else %>
        <% if latest %>
          <%= link_to 'csv', entries_path(format: 'csv'), title: 'export latest entries as csv' %>
        <% else %>
          <%= link_to 'csv', search_entries_path(format: 'csv', q: params[:q]), title: 'export entries as csv' %>
        <% end %>
      <% end %>
    </div>

    
  </div>
  
  <div class="bg-white p-3 overflow-ellipsis overflow-hidden"> 
    <% entries.each do |entry| %>
      <%= render 'shared/entry', entry: entry %>
    <% end %>
  
    <% if @pagy.pages > 1 %>
      <%== pagy_nav(@pagy).html_safe %>
    <% end %>
  </div>
<% else %>
  <div class="bg-white p-3 mt-5">
  <% if @feed %>
    <% if params[:q].blank? %>
      <p>There are no entries for this feed yet. Try again later!</p>
    <% else %>
       <p>Your search for - <strong><%= params[:q] %></strong> - did not match any entries into this feed. Try with another query!</p>
    <% end %>
  <% else %>
    <% if params[:q].blank? %>
      <p> You must specify a search query to get results. <a class="underline text-red-400" href="/entries/search?q=trend">I'm feeling lucky!</a></p>
    <% else%>
      <p>Your search for - <strong><%= params[:q] %></strong> - did not match any entries. Try with another query!</p>
    <% end %>
  <% end %>  
  </div>
<% end %>

app/views/shared/_entry.html.erb
<div class="mb-5 overflow-ellipsis overflow-hidden">
  <span title="feed rank" class="bg-yellow-400 text-white inline-flex items-center justify-center px-2 py-1 mr-0 text-xs leading-none rounded-sd"><%= entry.feed.rank.round %></span> 
  <a href="<%= entry.feed.url %>" title="<%= entry.feed.title %>" target="_blank" class="bg-blue-400 text-white inline-flex items-center justify-center px-2 py-1 mr-2 text-xs leading-none rounded-sd hover:underline">feed</a>
      
  <a target="_BLANK" class="no-underline hover:underline text-blue-700" href="<%= entry.url %>"><%= highlight(entry.title, params[:q]) %></a> <span class="text-gray-400">-</span> 
  
  <span class="text-gray-600 text-sm"><%= "#{time_ago_in_words(entry.published_at, include_seconds: true)} ago" %></span>
  
  <% case entry&.sentiment&.dig('type')%>
    <% when 'negative' %>
      <span class="bg-red-200 text-red-400 inline-flex items-center justify-center px-2 py-1 ml-2 text-xs leading-none rounded-md">negative</span>
    <% when 'positive' %>
      <span class="bg-green-200 text-green-600 inline-flex items-center justify-center px-2 py-1 ml-2 text-xs leading-none rounded-md">positive</span>
    <% when 'neutral' %>
      <span class="bg-gray-200 text-gray-500 inline-flex items-center justify-center px-2 py-1 ml-2 text-xs leading-none rounded-md">neutral</span>
  <% end %>
  
  <br>

  <div class="mb-1">
    <span class="font-light text-green-600"><%= entry.url %></span>
  </div>
  <span
    class="text-justify"><%= sanitize(highlight(entry.body.truncate(800, omission: '... (continue)'), params[:q]), tags: %w(strong em a mark), attributes: %w(href)) %></span>
  <div class="my-1">
    <% entry.categories.take(6).each do |category| %>
      <span class="bg-gray-100 text-gray-600 inline-flex items-center justify-center px-2 py-1 text-xs leading-none rounded-sd"><%= category %></span>
    <% end %>
  </div>
</div>

app/views/shared/_feeds.html.erb
<div class="bg-white p-3 overflow-ellipsis overflow-hidden">
  <% feeds.each do |feed| %>
    <%= render 'feed', feed: feed %>
  <% end %>

  <% if @pagy.pages > 1 %>
    <%== pagy_nav(@pagy).html_safe %>
  <% end %>
</div>