config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :feeds, only: %i[index new create] do
    member do
      get :entries
    end
  end

  resources :entries, only: [:index] do
    collection do
      get :search
    end
  end

  root 'static#index'

  namespace :api, defaults: { format: 'json' } do
    resources :search, only: '' do
      collection do
        get :entries
        get :feeds
      end
    end

    resources :webhooks

    resources :tokens, only: [:create] do
      collection do
        get :current
        post :refresh
      end
    end
    resources :feeds, only: %i[index show create] do
      collection do
        get :popular
      end
      resources :entries, only: %i[index show] do
        member do
          get :tags
        end
      end
      resources :logs, only: %i[index show]
      resources :webhooks
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-140621816-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-140621816-1');
    </script>
    <title>dato.rss - RSS search engine</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Davide Santangelo">
    <meta name="description" content="dato.rss - RSS search engine - a search engine that allows you to find RSS feeds easily">
    <meta name="keywords" content="rails api web RSS">
    <meta property="og:url" content="https://datorss.com">
    <meta property="og:image" content="https://datorss.com/logo.png">
    <meta property="og:image:width" content="300">
    <meta property="og:image:height" content="300">
    <meta property="og:image:alt" content="datorss">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="dato.rss - the best RSS search experience you can find">
    <meta property="og:title" content="dato.rss - the best RSS search experience you can find">
    <meta property="og:description" content="dato.rss - RSS search engine - a search engine that allows you to find RSS feeds easily">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": 'reload' %>
    <%= favicon_pack_tag 'favicon.png' %>
  </head>

  <body class="font-arial min-h-screen h-full bg-gray-100">
    <div class="px-6 pb-6 overflow-ellipsis overflow-hidden">
      <div class="my-4">
        <% if params[:controller] == 'feeds' %>
          <% case params[:action] %>
            <% when 'entries' %>
              <%= link_to 'dato.rss', root_path, class: 'inline-block align-middle py-2 text-xl underline text-green-600', title: 'back to homepage'%>  <span class="inline-block align-middle py-2 text-xl text-blue-600"> / </span>
              <%= link_to 'feeds.rss', feeds_path, class: 'inline-block align-middle py-2 text-xl underline text-blue-600', title: 'back to homepage'%>  <span class="inline-block align-middle py-2 text-xl text-blue-600"> / </span>
              <span class="inline-block align-middle py-2 text-xl text-white bg-blue-600 px-2"> <%= @feed.title %> </span>
              <span class="inline-block align-middle py-2 text-xl text-gray-600"> / entries </span>
            <% when 'index' %>
              <%= link_to 'dato.rss', root_path, class: 'inline-block align-middle py-2 text-xl text-light underline text-green-600', title: 'back to homepage'%>  <span class="inline-block align-middle py-2 text-xl text-blue-600"> / feeds </span>
            <% when 'new' %>
              <%= link_to 'dato.rss', root_path, class: 'inline-block align-middle py-2 text-xl underline text-green-600', title: 'back to homepage'%>  <span class="inline-block align-middle py-2 text-xl text-blue-600"> / </span>
              <%= link_to 'feeds.rss', feeds_path, class: 'inline-block align-middle py-2 text-xl underline text-blue-600', title: 'back to homepage'%>  <span class="inline-block align-middle py-2 text-xl text-blue-600"> / </span>
              <span class="inline-block align-middle py-2 text-xl bg-gray-600 text-white px-2"> add </span>
          <% end %>
        <% end %>

        <% if params[:controller] == 'entries' %>
          <%= link_to 'dato.rss', root_path, class: 'inline-block align-middle py-2 text-xl underline text-green-600', title: 'back to homepage'%>  <span class="inline-block align-middle py-2 text-xl text-blue-600"> / </span>
          <%= link_to 'feed.rss', feeds_path, class: 'inline-block align-middle py-2 text-xl underline text-blue-600', title: 'back to feeds' %> <span class="inline-block align-middle py-2 text-xl text-blue-600"> / </span>
          <span class="inline-block align-middle py-2 text-xl text-white px-2 bg-gray-600"> <%= params[:action] == 'index' ? 'latest' : params[:q].presence || 'blank query' %> </span>
          <span class="inline-block align-middle py-2 text-xl text-gray-600"> / entries </span>
        <% end %>

        <% if params[:controller] == 'feeds' %>
          <% case params[:action] %>
            <% when 'new' %>
              <%= link_to 'back', feeds_path, title: 'back to search', class: "rounded float-right inline-block align-middle py-1 text-xl text-gray-600 underline" %>
            <% when 'index', 'entries' %>
              <%= link_to 'new [+]', new_feed_path, title: 'add new feed', class: "rounded float-right inline-block align-middle py-1 text-xl text-gray-600 hover:underline" %>
          <% end %>
        <% end %>
      </div>

      <% if params[:action] == 'new' %>
        <%= form_for Feed.new do |form| %>
          <%= form.text_field :url, class: 'appearance-none border border-gray-400 py-3 px-3 text-grey-darkest w-full rounded', placeholder: 'feed:https://example.com/rss', type: 'search', autofocus: true, onkeydown: 'if (event.keyCode === 13) { $(\'.loading\').removeClass(\'hidden\'); $(\'.stats\').hide() }' %>
        <% end %>
      <% else %>
        <%= form_tag(@feed ? entries_feed_path(@feed) : search_entries_path, method: :get) do %>
          <%= text_field_tag 'q', params[:q], class: 'appearance-none border border-gray-400 py-3 px-3 text-grey-darkest w-full rounded', placeholder: 'what are you looking for?', type: 'search', autofocus: true %>
        <% end %>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-140621816-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-140621816-1');
    </script>

    <title>dato.rss - RSS search engine</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Davide Santangelo">
    <meta name="description" content="dato.rss - RSS search engine - a search engine that allows you to find RSS feeds easily">
    <meta name="keywords" content="rails api web RSS">
    <meta property="og:url" content="https://datorss.com">
    <meta property="og:image" content="https://datorss.com/logo.png">
    <meta property="og:image:width" content="300">
    <meta property="og:image:height" content="300">
    <meta property="og:image:alt" content="datorss">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="dato.rss - the best RSS search experience you can find">
    <meta property="og:title" content="dato.rss - the best RSS search experience you can find">
    <meta property="og:description" content="dato.rss - RSS search engine - a search engine that allows you to find RSS feeds easily">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_pack_tag 'favicon.png' %>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script>
      window.addEventListener("load", function () {
        window.cookieconsent.initialise({
          "palette": {
            "popup": {
              "background": "#252e39"
            },
            "button": {
              "background": "#14a7d0"
            }
          },
          "content": {
            "message": "We use cookies to help our site work and to understand how it is used. By continuing to browse the site you're agreeing to our use of cookies."
          }
        })
      });
    </script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="https://gumroad.com/js/gumroad.js"></script>

  </head>


  <span class="loading hidden absolute top-5 left-5">
    <i class="fas fa-circle-notch fa-spin text-2xl text-green-400"></i>
  </span>
  
  <body class="font-arial h-full">
    <%= yield %>
    <div class="text-center w-full justify-self-center text-lg">
    <a class="gumroad-button mt-20" href="https://davidesantangelo.gumroad.com/l/nkyymb" data-gumroad-overlay-checkout="true">Buy SQL dump on</a>
    </div>
  </body>

  <footer class="absolute bottom-5 text-center w-full justify-self-center text-lg">
    <span class="text-gray-400">{ author: <a title="Davide Santangelo" href="https://twitter.com/daviducolo" title="made by Davide Santangelo" class="no-underline text-green-400  hover:text-blue-600">"@daviducolo"</a>, source: <a class="text-green-400 no-underline hover:text-black" href="https://github.com/dato-ai/dato.rss">"github"</a> }</span>
  </footer>
</html>